name: Build Rust Project with Optimizations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, llvm-tools-preview

    - name: Build Project with Optimizations
      run: cargo build --release
      env:
        RUSTFLAGS: '-C opt-level=3 -C target-cpu=native'


    # - name: Run tests
    #   run: cargo test --verbose

    # - name: Run Clippy
    #   run: cargo clippy --all-targets --all-features

    # - name: Install cargo-llvm-cov
    #   run: cargo install cargo-llvm-cov

    # - name: Install dependencies
    #   run: sudo apt-get install -y jq bc

    # - name: Run tests and generate coverage report
    #   run: |
    #     cargo llvm-cov clean --workspace
    #     cargo llvm-cov --json --output-path=coverage.json

    # - name: Check coverage
    #   id: coverage-check
    #   run: |
    #     COVERAGE=$(jq '.data[0].totals.lines.pct' < coverage.json)
    #     echo "Coverage is $COVERAGE%"
    #     if (( $(echo "$COVERAGE < 50" | bc -l) )); then
    #       echo "Code coverage is below 50%"
    #       exit 1
    #     fi
    
    # - name: Upload to codecov.io
    #   uses: codecov/codecov-action@v1.0.2
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}}
    
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    
    # - name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #     push: true
    #     tags: docker.io/shazindia86/githubactionsdemo:${{ github.sha }}

    #  - name: Run Trivy vulnerability scanner
    #    uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
    #    with:
    #     image-ref: 'docker.io/shazindia86/githubactionsdemo:${{ github.sha }}'
    #     format: 'template'
    #     template: '@/contrib/sarif.tpl'
    #     output: 'trivy-results.sarif'
